# I use Topgrade to manage overall system and core tools, not the dependencies for
# individual software projects. This prevents a global update from accidentally
# breaking a project that depends on specific package versions.

[misc]
# A list of steps to exclusively run. All other steps will be skipped
only = [
    "brew_formula",
    "brew_cask",
    "mas",
    "system",
    # Disable asdf update until after topgrade 16.0.4
    # There is a fix for parsing asdf version on deck for the next release after 16.0.4
    # "asdf",
    "shell",
    "vscode",
    "chezmoi",
    "github_cli_extensions",
]

[brew]
# Make brew upgrades applications (casks) that are normally skipped because
# they update themselves.

# This has some risks:
#  * May fail or corrupt an application if it's updated while running
#  * Can conflict with the app's built-in updater, causing redundant downloads or failures
#  * Bypasses the app's native updater, potentially skipping important configuration migrations
#  * Can cause Homebrew's version tracking to become out of sync with the actual app version
#  * Can force abrupt application restarts, disrupting your workflow
# However, while these risks are possible, they haven't impacted me yet.

greedy_cask = true
